import { Inter } from "next/font/google";
import "./globals.css";
import Layout from "@/components/ui/Layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "FullStack Portfolio Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout>{children}</Layout>
        </body>
    </html>
  );
}
