import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import Layout from "@/components/ui/Layout";

const rubik = Rubik({ subsets: ["latin"], variable: "--font-rubik" });

export const metadata: Metadata = {
  title: "FullStack Portfolio Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
